name: Upsert Pull Requests
description: Automate upserting pull requests
branding:
  icon: book
  color: blue
inputs:
  token:
    description: Token for Github
    required: true
  paths:
    description: |
      A JSON list of strings with the paths that will be used to determine the packages that changed
    required: true
  environmentName:
    description: |
      The environment to which to create the PR against
    required: true
runs:
  using: docker
  image: Dockerfile
