name: Create Changeset
description: Automate adding a changeset for simple pull requests
branding:
  icon: book
  color: blue
inputs:
  ignoredPackages:
    description: |
      A comma separated list of package names that will be ignored from changeset creation
    required: false
  token:
    description: Token for Github
    required: true
  paths:
    description: |
      A JSON list of strings with the paths that will be used to determine the packages that changed
    required: true
runs:
  using: docker
  image: Dockerfile
