name: Affected Paths
description: Outputs paths affected by a range of commits
branding:
  icon: book
  color: blue
inputs:
  head:
    description: |
      git ref to use as head.
      You can use github.pull_request.head.ref if you're on a PR context.
      Defaults to 'HEAD'
    default: 'HEAD'
  base:
    description: |
      git ref to use as base.
      You can use github.pull_request.base.ref if you're on a PR context.
      Defaults to 'HEAD~1'
    default: 'HEAD~1'
  filter:
    description: |
      regex to filter out paths from the affected logic.
runs:
  using: docker
  image: Dockerfile
