name: Changeset Action
description: Automate adding a changeset for simple pull requests
branding:
  icon: book
  color: blue
runs:
  using: docker
  image: Dockerfile
  pre-entrypoint: 'cp yarn.lock .github/actions/tagger'
