name: Changeset Action
description: Automate adding a changeset for simple pull requests
branding:
  icon: book
  color: blue
inputs:
  token:
    description: Token for Github
    required: true
  packageScope:
    description: The scope of the packages
    required: true
runs:
  using: docker
  image: Dockerfile
