name: Validate
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Lint PR title
        uses: amannn/action-semantic-pull-request@v3.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          subjectPattern: ^(?![A-Z]).+$
          wip: true
      - name: Test stuff
        run: echo 'Testing stuff'
