name: Version Packages
on:
  push:
    branches:
      - main
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false
jobs:
  version-packages:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1
        env:
          CYPRESS_INSTALL_BINARY: 0
      - name: Copy lockfile to actions
        run: |
          cp yarn.lock .github/actions/create-changeset
          cp yarn.lock .github/actions/tagger
      - name: Create changeset
        uses: ./.github/actions/create-changeset
      - name: Version packages
        run: yarn run version-packages
      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(changeset): bump package versions"
          commit_options: '--no-verify --signoff'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create tags
        uses: ./.github/actions/tagger
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
